# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc44b822cb21702ae7697dbf57ae7fe24056f03686e6cc1447fa0c76801cd0a5b8f9ed621bc2b461e2ca3dd1d78fa5772c1704dee16368d39391914bb12f40ad

test:
  secret_key_base: 69150254488648e47c402ca6d172ae49731eb9c9dab3f82a835ea33d186da1c47ed165180dc2ce018a8bc5aa5e3a6b80ce0640da17aa2001b540e904b9343eb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
